figures:
	python build_paper_assets.py

pdf:
	latexmk -pdf -interaction=nonstopmode manuscript.tex

clean:
	rm -f manuscript.aux manuscript.bbl manuscript.blg manuscript.fdb_latexmk manuscript.fls manuscript.log manuscript.out
